vg/config/routes.rb
Rails.application.routes.draw do
  resources :volumes

  resources :ip_addresses

  resources :images

  resources :flavors

  resources :nodes

  get 'openstack_actions/action'
  get 'openstack_actions/get_cookbooks'
  get 'openstack_actions/populate_flavors'
  get 'openstack_actions/server_status'
  get 'openstack_actions/servers_status'

  resources :openstack_users

  devise_for :users
  resources :ideas

   root 'openstack_users#index'

end

vg/app/models/node.rb
class Node < ActiveRecord::Base
	  belongs_to :openstack_user

	def self.for_openstack_user(openstack)
		where("openstack_user_id = #{openstack}")
  end


end

vg/app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :set_node, only: [:show, :edit, :update, :destroy]

  # GET /nodes
  # GET /nodes.json
  def index
    if (params[:openstack_user].present?)
      session[:openstack_user] = params[:openstack_user]
      @openstack = Openstackapi.new(params[:openstack_user])
      if (session[:updated_floavors] == "")
        session[:updated_floavors] = "populated"
        @openstack.populate_flavors
      end
      @nodes = Node.for_openstack_user(params[:openstack_user])
      @flavors = Array.new
      @images = Array.new
      @volumes = Array.new
      @ipaddresses = Array.new
      @nodes.each do |node|
        @flavors.push(node.flavor)
        @images.push(node.image)
        @volumes.push(node.volume)
        @ipaddresses.push(node.ipaddress)
      end
    else
      session[:openstack_user] = ""
      @nodes = Node.all
    end
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
  end

  # GET /nodes/new
  def new
    @node = Node.new
  end

  # GET /nodes/1/edit
  def edit
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(node_params)

    respond_to do |format|
      if @node.save
        format.html { redirect_to nodes_url(:openstack_user => session[:openstack_user]), notice: 'Node was successfully created.' }
        format.json { render :show, status: :created, location: @node }
      else
        format.html { render :new }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nodes/1
  # PATCH/PUT /nodes/1.json
  def update
    respond_to do |format|
      if @node.update(node_params)
        format.html { redirect_to nodes_url(:openstack_user => session[:openstack_user]), notice: 'Node was successfully updated.' }
        format.json { render :show, status: :ok, location: @node }
      else
        format.html { render :edit }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node.destroy
    respond_to do |format|
      format.html { redirect_to nodes_url(:openstack_user => session[:openstack_user]), notice: 'Node was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node
      @node = Node.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def node_params
      params.require(:node).permit(:openstack_user_id, :name, :recipe, :apps)
    end

end

vg/app/helpers/nodes_helper.rb
module NodesHelper
end

vg/app/views/nodes/_form.html.erb
<%= form_for(@node) do |f| %>
  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% @node.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag 'node[openstack_user_id]', session[:openstack_user] %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :recipe %><br>
    <%= f.text_field :recipe %>
  </div>
  <div class="field">
    <%= f.label :apps %><br>
    <%= f.text_field :apps %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

vg/app/views/nodes/edit.html.erb
<h1>Editing node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path(:openstack_user => session[:openstack_user]) %>

vg/app/views/nodes/index.html.erb
<h1>Listing nodes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Recipe</th>
      <th>Apps</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% flavors_position = 0 %>
    <% @nodes.each do |node| %>
      <tr>
        <td><%= node.name %></td>
        <td><%= node.recipe %></td>
        <td><%= node.apps %></td>
        <td>
          <table class="group">
            <tr><td><%= link_to 'Edit', edit_node_path(node) %></td></tr>
            <tr><td><%= link_to 'Destroy', node_path(node), method: :delete %></td></tr>
          </table>
        </td>
        <td>
          <div id="start_go_<%= node.name %>">
            <table class="group">
                <%= form_tag("/openstack_actions/action", method: "get") do %>
                <tr><td>
                  <%= collection_select(:flavors, :flavors, Flavor.all, :flavor_id, :name, {:selected => @flavors[flavors_position]},
                    {:class => "medium_drop_down_xx_go_xx"}) %>
                </td>
                <td>
                  <%= collection_select(:images, :images, Image.all, :image_id, :name, {:selected => @images[flavors_position]},
                    {:class => "medium_drop_down_xx_go_xx"}) %>
                  <%= hidden_field_tag 'openstack_user', node.openstack_user_id %>
                  <%= hidden_field_tag 'recipe', node.recipe %>
                  <%= hidden_field_tag 'node', node.name %>
                  <%= hidden_field_tag 'apps', node.apps %>
                  <%= hidden_field_tag 'name', node.name %>
                  <%= hidden_field_tag 'activity', :start %>
                </td></tr>
                <tr><td colspan=2 align="center">
                  <%=  submit_tag("Start Instance", {:disabled => false, :class => "action_xx_go_xx"}) %>
                </td></tr>
                <%  end %>
            </table>
            </div>
          <div id="start_stop_<%= node.name %>">
            <table class="group">
                <%= form_tag("/openstack_actions/action", method: "get") do %>
                <tr><td>
                    <%= collection_select(:flavors, :flavors, Flavor.all, :flavor_id, :name, {:selected => @flavors[flavors_position]},
                      {:class => "medium_drop_down_xx_stop_xx", :disabled => "true"}) %>                  
                </td>
                <td>
                  <%= collection_select(:images, :images, Image.all, :image_id, :name, {:selected => @images[flavors_position]},
                    {:class => "medium_drop_down_xx_stop_xx", :disabled => "true"}) %>
                  <%= hidden_field_tag 'openstack_user', node.openstack_user_id %>
                  <%= hidden_field_tag 'recipe', node.recipe %>
                  <%= hidden_field_tag 'node', node.name %>
                  <%= hidden_field_tag 'apps', node.apps %>
                  <%= hidden_field_tag 'name', node.name %>
                  <%= hidden_field_tag 'activity', :start %>
                </td></tr>
                <tr><td colspan=2 align="center">
                  <%=  submit_tag("Start Instance", {:disabled => true, :class => "action_xx_stop_xx"}) %>
                </td></tr>
                <%  end %>
            </table>
          </div>
        </td>
        <td>
          <div id="volume_go_<%= node.name %>">
            <table class="group">
              <%= form_tag("/openstack_actions/action", method: "get") do %>
              <tr><td align="center">
                <%=  collection_select(:volumes, :volumes, Volume.all, :volume_id, :name, {:selected => @volumes[flavors_position]},
                       {:class => "medium_drop_down_xx_go_xx"}) %>
              </td></tr>
              <tr><td align="center">
                <%=  submit_tag("Attach Volume", {:disabled => false, :class => "action_xx_go_xx"}) %>
              </td></tr>
                <%= hidden_field_tag 'openstack_user', node.openstack_user_id %>
                <%= hidden_field_tag 'recipe', node.recipe %>
                <%= hidden_field_tag 'node', node.name %>
                <%= hidden_field_tag 'apps', node.apps %>
                <%= hidden_field_tag 'name', node.name %>
                <%= hidden_field_tag 'activity', :attach_volume %>
              </td></tr>
              <%  end %>
            </table>
          </div>
          <div id="volume_stop_<%= node.name %>">
            <table class="group">
              <%= form_tag("/openstack_actions/action", method: "get") do %>
              <tr><td align="center">
                <%=  collection_select(:volumes, :volumes, Volume.all, :volume_id, :name, 
                      {:selected => @volumes[flavors_position]}, {:disabled => "true", :class => "medium_drop_down_xx_stop_xx"}) %>
              </td></tr>
              <tr><td align="center">
                <%=  submit_tag("Attach Volume", {:disabled => true, :class => "action_xx_stop_xx"}) %>
              </td></tr>
                <%= hidden_field_tag 'openstack_user', node.openstack_user_id %>
                <%= hidden_field_tag 'recipe', node.recipe %>
                <%= hidden_field_tag 'node', node.name %>
                <%= hidden_field_tag 'apps', node.apps %>
                <%= hidden_field_tag 'name', node.name %>
                <%= hidden_field_tag 'activity', :attach_volume %>
              </td></tr>
              <%  end %>
            </table>
          </div>  
        </td>

        <td>
           <div id="ipaddress_go_<%= node.name %>">
            <table class="group">
              <tr><td colspan=2 align="center">
                <%=  form_tag("/openstack_actions/action", method: "get") do %>
                <%=  collection_select(:ip_address, :ip_address, IpAddress.all, :ip_address, :ip_address,
                       {:selected => @ipaddresses[flavors_position]}, {:class => "medium_drop_down_xx_go_xx"}) %>
                <%= hidden_field_tag 'openstack_user', node.openstack_user_id %>
                <%= hidden_field_tag 'name', node.name %>
                <%= hidden_field_tag 'activity', :assign_ip_address %>
              </td></tr>
              <tr>
                <td>
                  <%=  submit_tag("Allocate IP", {:disabled => false, :class => "action_xx_go_xx"}) %>
                <%  end %>
                </td>
                <td>
                 <%= form_tag("/openstack_actions/action", method: "get") do %>
                    <%= hidden_field_tag 'openstack_user', node.openstack_user_id %>
                    <%= hidden_field_tag 'name', node.name %>
                    <%= hidden_field_tag 'activity', :deallocate_ip_address %>
                    <%=  submit_tag("Deallocate IP", {:disabled => false, :class => "action_xx_go_xx"}) %>
                  <%  end %>
                </td>
              </tr>
            </table>
          </div>
          <div id="ipaddress_stop_<%= node.name %>">
            <table class="group">
              <tr><td colspan=2 align="center">
                <%=  form_tag("/openstack_actions/action", method: "get") do %>
                <%=  collection_select(:ip_address, :ip_address, IpAddress.all, :ip_address, :ip_address,
                       {:selected => @ipaddresses[flavors_position]}, {:disabled => "true", :class => "medium_drop_down_xx_stop_xx"}) %>
                <%= hidden_field_tag 'openstack_user', node.openstack_user_id %>
                <%= hidden_field_tag 'name', node.name %>
                <%= hidden_field_tag 'activity', :assign_ip_address %>
              </td></tr>
              <tr>
                <td>
                   <%=  submit_tag("Allocate IP", {:disabled => true, :class => "action_xx_stop_xx"}) %>
                <%  end %>
                </td>
                <td>
                 <%= form_tag("/openstack_actions/action", method: "get") do %>
                    <%= hidden_field_tag 'openstack_user', node.openstack_user_id %>
                    <%= hidden_field_tag 'name', node.name %>
                    <%= hidden_field_tag 'activity', :deallocate_ip_address %>
                    <%=  submit_tag("Deallocate IP", {:disabled => true, :class => "action_xx_stop_xx"}) %>
                  <%  end %>
                </td>
            </table>
          </div>  
        </td>
        <td>
          <div id="control_go_<%= node.name %>">
            <table class="group">
              <tr>
                <td align="center" style="vertical-align:bottom">
                  <%= form_tag("/openstack_actions/action", method: "get") do %>
                    <%= hidden_field_tag 'openstack_user', node.openstack_user_id %>
                    <%= hidden_field_tag 'recipe', node.recipe %>
                    <%= hidden_field_tag 'node', node.name %>
                    <%= hidden_field_tag 'apps', node.apps %>
                    <%= hidden_field_tag 'name', node.name %>
                    <%= hidden_field_tag 'activity', :bootstrap_instance %>
                    <%=  submit_tag("Run Chef", {:disabled => false, :class => "action_xx_go_xx"}) %>
                  <%  end %>
                </td>
              </tr>
              <tr>
                <td>
                  <%= form_tag("/openstack_actions/action", method: "get") do %>
                    <%= hidden_field_tag 'openstack_user', node.openstack_user_id %>
                    <%= hidden_field_tag 'name', node.name %>
                    <%= hidden_field_tag 'activity', :terminate_instance %>
                    <%=  submit_tag("Terminate", {:disabled => false, :class => "action_xx_go_xx"}) %>
                  <%  end %>
                </td>
              </tr>
            </table>
          </div>
          <div id="control_stop_<%= node.name %>">
            <table class="group">
              <tr>
                <td align="center" style="vertical-align:bottom">
                  <%= form_tag("/openstack_actions/action", method: "get") do %>
                    <%= hidden_field_tag 'openstack_user', node.openstack_user_id %>
                    <%= hidden_field_tag 'recipe', node.recipe %>
                    <%= hidden_field_tag 'node', node.name %>
                    <%= hidden_field_tag 'apps', node.apps %>
                    <%= hidden_field_tag 'name', node.name %>
                    <%= hidden_field_tag 'activity', :bootstrap_instance %>
                    <%=  submit_tag("Run Chef", {:disabled => true, :class => "action_xx_stop_xx"}) %>
                  <%  end %>
                </td>
              </tr>
              <tr>
                <td>
                  <%= form_tag("/openstack_actions/action", method: "get") do %>
                    <%= hidden_field_tag 'openstack_user', node.openstack_user_id %>
                    <%= hidden_field_tag 'name', node.name %>
                    <%= hidden_field_tag 'activity', :terminate_instance %>
                    <%=  submit_tag("Terminate", {:disabled => true, :class => "action_xx_stop_xx"}) %>
                  <%  end %>
                </td>
              </tr>
            </table>
          </div>
        </td>
        <td id="<%= node.name %>"></td>
        <script>
          update_server_status('<%= node.openstack_user_id %>', '<%= node.name%>');
          $(document).ready(function($){
              window.setInterval(function() {update_server_status('<%= node.openstack_user_id %>', '<%= node.name %>')}, 5000);
            });
        </script>
      </tr>
      <% flavors_position =+ 1 %>
    <% end %> 
  </tbody>
</table>

<br>

<%= link_to 'New Node', new_node_path() %>

vg/app/views/nodes/new.html.erb
<h1>New node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path(:openstack_user => session[:openstack_user]) %>

vg/app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @node.name %>
</p>

<p>
  <strong>Recipe:</strong>
  <%= @node.recipe %>
</p>

<p>
  <strong>apps:</strong>
  <%= @node.apps %>
</p>


<%= link_to 'Edit', edit_node_path %> |
<%= link_to 'Back', nodes_path(:openstack_user => session[:openstack_user]) %>