vg/config/routes.rb
Rails.application.routes.draw do
  resources :volumes

  resources :ip_addresses

  resources :images

  resources :flavors

  resources :nodes

  get 'openstack_actions/action'
  get 'openstack_actions/get_cookbooks'
  get 'openstack_actions/populate_flavors'
  get 'openstack_actions/server_status'
  get 'openstack_actions/servers_status'

  resources :openstack_users

  devise_for :users
  resources :ideas

   root 'openstack_users#index'

end

vg/app/models/openstack_user.rb
class OpenstackUser < ActiveRecord::Base
	has_many :nodes
end

vg/app/controllers/openstack_users_controller.rb
class OpenstackUsersController < ApplicationController
  before_action :set_openstack_user, only: [:show, :edit, :update, :destroy]

  # GET /openstack_users
  # GET /openstack_users.json
  def index
    session[:updated_floavors] = ""
    @openstack_users = OpenstackUser.all
  end

  # GET /openstack_users/1
  # GET /openstack_users/1.json
  def show
  end

  # GET /openstack_users/new
  def new
    @openstack_user = OpenstackUser.new
  end

  # GET /openstack_users/1/edit
  def edit
  end

  # POST /openstack_users
  # POST /openstack_users.json
  def create
    @openstack_user = OpenstackUser.new(openstack_user_params)

    respond_to do |format|
      if @openstack_user.save
        format.html { redirect_to @openstack_user, notice: 'Openstack user was successfully created.' }
        format.json { render :show, status: :created, location: @openstack_user }
      else
        format.html { render :new }
        format.json { render json: @openstack_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /openstack_users/1
  # PATCH/PUT /openstack_users/1.json
  def update
    respond_to do |format|
      if @openstack_user.update(openstack_user_params)
        format.html { redirect_to @openstack_user, notice: 'Openstack user was successfully updated.' }
        format.json { render :show, status: :ok, location: @openstack_user }
      else
        format.html { render :edit }
        format.json { render json: @openstack_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /openstack_users/1
  # DELETE /openstack_users/1.json
  def destroy
    @openstack_user.destroy
    respond_to do |format|
      format.html { redirect_to openstack_users_url, notice: 'Openstack user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_openstack_user
      @openstack_user = OpenstackUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def openstack_user_params
      params.require(:openstack_user).permit(:os_username, :os_password, :os_auth_url, :chef_server_url, :client_name, :signing_key_file)
    end
end

vg/app/helpers/openstack_users_helper.rb
module OpenstackUsersHelper
end

vg/app/views/openstack_users/_form.html.erb
<%= form_for(@openstack_user) do |f| %>
  <% if @openstack_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@openstack_user.errors.count, "error") %> prohibited this openstack_user from being saved:</h2>

      <ul>
      <% @openstack_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :os_username %><br>
    <%= f.text_field :os_username %>
  </div>
  <div class="field">
    <%= f.label :os_password %><br>
    <%= f.text_field :os_password %>
  </div>
  <div class="field">
    <%= f.label :os_auth_url %><br>
    <%= f.text_field :os_auth_url %>
  </div>
  <div class="field">
    <%= f.label :chef_server_url %><br>
    <%= f.text_field :chef_server_url %>
  </div>
  <div class="field">
    <%= f.label :client_name %><br>
    <%= f.text_field :client_name %>
  </div>
  <div class="field">
    <%= f.label :signing_key_file %><br>
    <%= f.text_field :signing_key_file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

vg/app/views/openstack_users/edit.html.erb
<h1>Editing openstack_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @openstack_user %> |
<%= link_to 'Back', openstack_users_path %>

vg/app/views/openstack_users/index.html.erb
<h1>Listing openstack_users</h1>

<table>
  <thead>
    <tr>
      <th>Os username</th>
      <th>Os password</th>
      <th>Os auth url</th>
      <th>Chef Server URL</th>
      <th>Client Name</th>
      <th>Signing Key File</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @openstack_users.each do |openstack_user| %>
      <tr>
        <td><%= openstack_user.os_username %></td>
        <td><%= openstack_user.os_password %></td>
        <td><%= openstack_user.os_auth_url %></td>
        <td><%= openstack_user.chef_server_url %></td>
        <td><%= openstack_user.client_name %></td>
        <td><%= openstack_user.signing_key_file %></td>
        <td><%= link_to 'Show', openstack_user %></td>
        <td><%= link_to 'Edit', edit_openstack_user_path(openstack_user) %></td>
        <td><%= link_to 'Destroy', openstack_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Nodes', nodes_path(:openstack_user => openstack_user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Openstack user', new_openstack_user_path %>

vg/app/views/openstack_users/new.html.erb
<h1>New openstack_user</h1>

<%= render 'form' %>

<%= link_to 'Back', openstack_users_path %>

vg/app/views/openstack_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Os username:</strong>
  <%= @openstack_user.os_username %>
</p>

<p>
  <strong>Os password:</strong>
  <%= @openstack_user.os_password %>
</p>

<p>
  <strong>Os auth url:</strong>
  <%= @openstack_user.os_auth_url %>
</p>

<%= link_to 'Edit', edit_openstack_user_path(@openstack_user) %> |
<%= link_to 'Back', openstack_users_path %>