vg/config/routes.rb
Rails.application.routes.draw do
  resources :volumes

  resources :ip_addresses

  resources :images

  resources :flavors

  resources :nodes

  get 'openstack_actions/action'
  get 'openstack_actions/get_cookbooks'
  get 'openstack_actions/populate_flavors'
  get 'openstack_actions/server_status'
  get 'openstack_actions/servers_status'

  resources :openstack_users

  devise_for :users
  resources :ideas

   root 'openstack_users#index'

end

vg/app/models/flavor.rb
class Flavor < ActiveRecord::Base
end

vg/app/controllers/flavors_controller.rb
class FlavorsController < ApplicationController
  before_action :set_flavor, only: [:show, :edit, :update, :destroy]

  # GET /flavors
  # GET /flavors.json
  def index
    @flavors = Flavor.all
  end

  # GET /flavors/1
  # GET /flavors/1.json
  def show
  end

  # GET /flavors/new
  def new
    @flavor = Flavor.new
  end

  # GET /flavors/1/edit
  def edit
  end

  # POST /flavors
  # POST /flavors.json
  def create
    @flavor = Flavor.new(flavor_params)

    respond_to do |format|
      if @flavor.save
        format.html { redirect_to @flavor, notice: 'Flavor was successfully created.' }
        format.json { render :show, status: :created, location: @flavor }
      else
        format.html { render :new }
        format.json { render json: @flavor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flavors/1
  # PATCH/PUT /flavors/1.json
  def update
    respond_to do |format|
      if @flavor.update(flavor_params)
        format.html { redirect_to @flavor, notice: 'Flavor was successfully updated.' }
        format.json { render :show, status: :ok, location: @flavor }
      else
        format.html { render :edit }
        format.json { render json: @flavor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flavors/1
  # DELETE /flavors/1.json
  def destroy
    @flavor.destroy
    respond_to do |format|
      format.html { redirect_to flavors_url, notice: 'Flavor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flavor
      @flavor = Flavor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flavor_params
      params.require(:flavor).permit(:name, :flavor_id)
    end

end

vg/app/helpers/flavors_helper.rb
module FlavorsHelper
end

vg/app/views/flavors/_form.html.erb
<%= form_for(@flavor) do |f| %>
  <% if @flavor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flavor.errors.count, "error") %> prohibited this flavor from being saved:</h2>

      <ul>
      <% @flavor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :flavor_id %><br>
    <%= f.text_field :flavor_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

vg/app/views/flavors/edit.html.erb
<h1>Editing flavor</h1>

<%= render 'form' %>

<%= link_to 'Show', @flavor %> |
<%= link_to 'Back', flavors_path %>

vg/app/views/flavors/index.html.erb
<h1>Listing flavors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Flavor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flavors.each do |flavor| %>
      <tr>
        <td><%= flavor.name %></td>
        <td><%= flavor.flavor_id %></td>
        <td><%= link_to 'Show', flavor %></td>
        <td><%= link_to 'Edit', edit_flavor_path(flavor) %></td>
        <td><%= link_to 'Destroy', flavor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flavor', new_flavor_path %>

vg/app/views/flavors/new.html.erb
<h1>New flavor</h1>

<%= render 'form' %>

<%= link_to 'Back', flavors_path %>

vg/app/views/flavors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @flavor.name %>
</p>

<p>
  <strong>Flavor:</strong>
  <%= @flavor.flavor_id %>
</p>

<%= link_to 'Edit', edit_flavor_path(@flavor) %> |
<%= link_to 'Back', flavors_path %>